app = "anexarexames"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    MISE_PYTHON_COMPILE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
